# Generated by Django 4.1 on 2022-08-20 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('editorial', models.CharField(max_length=100, verbose_name='Editorial')),
                ('paginas', models.IntegerField(verbose_name='Numero de Paginas')),
                ('publicacion', models.CharField(max_length=100, verbose_name='Publicacion')),
                ('clasificacion', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Ficcion', 'Ficcion'), ('Suspenso', 'Suspenso'), ('Ciencia Ficcion', 'Ciencia Ficcion'), ('Terror', 'Terror'), ('Policial', 'Policial')], default='Seleccionar', max_length=15, verbose_name='Clasificacion')),
                ('sinopsis', models.TextField(max_length=3000, verbose_name='Sinopsis')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('autor', models.ManyToManyField(to='libros.autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['id'],
            },
        ),
    ]
