# Generated by Django 4.1 on 2022-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(related_name='autor', to='libros.autor'),
        ),
    ]
